export const FETCH_WEATHER_INFO = 'FETCH_WEATHER_INFO';
export const FETCH_WEATHER_INFO_FAILED = 'FETCH_WEATHER_INFO_FAILED';
export const RECEIVE_WEATHER_INFO = 'RECEIVE_WEATHER_INFO';

export const ADD_CITY = 'ADD_CITY';
export const REMOVE_CITY = 'REMOVE_CITY';
